name: daily_news
description: An app to check out latest news
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management / Dependency Injection
  flutter_riverpod: ^1.0.3
  
  # Data Sources
  hive_flutter: ^1.1.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.7


flutter:
  uses-material-design: true