// Mocks generated by Mockito 5.0.17 from annotations
// in daily_news/test/features/home/data/repositories/articles_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:daily_news/features/home/data/datasources/articles_remote_data_source.dart'
    as _i2;
import 'package:daily_news/features/home/domain/entities/article_entity.dart'
    as _i4;
import 'package:daily_news/features/home/domain/usecases/get_articles_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ArticlesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesRemoteDataSource extends _i1.Mock
    implements _i2.ArticlesRemoteDataSource {
  MockArticlesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ArticleEntity>> getArticles(
          _i5.ArticlesType? articlesType) =>
      (super.noSuchMethod(Invocation.method(#getArticles, [articlesType]),
              returnValue:
                  Future<List<_i4.ArticleEntity>>.value(<_i4.ArticleEntity>[]))
          as _i3.Future<List<_i4.ArticleEntity>>);
}
